default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  port: 5432
  pool: 55

development:
  <<: *default
  database: dev_trail_development

test: &test
  <<: *default
  database: dev_trail_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
